apiVersion: batch/v1
kind: Job
metadata:
  name: bot-fleet-job
  labels:
    app: bot-fleet
spec:
  completions: 50
  parallelism: 50
  template:
    metadata:
      labels:
        app: bot-agent
    spec:
      containers:
      - name: bot-agent
        image: iicpc/bot-agent:latest
        env:
        - name: TARGET_URL
          valueFrom:
            fieldRef:
              fieldPath: metadata.annotations['target-url']
        args:
          - "--bots=20"
          - "--orders=500"
        resources:
          limits:
            cpu: "500m"
            memory: "128Mi"
          requests:
            cpu: "250m"
            memory: "64Mi"
      restartPolicy: Never
  backoffLimit: 3
